name: tailscale

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v2

      - name: Tailscale 动作 =>
        uses: ./
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: 在网络地图中检查
        run:
          tailscaled status | grep -q hello

